#!/bin/sh
feh --bg-scale ~/.local/wallpapers/wall1.jpg ~/.local/wallpapers/wall2.jpg &
pipewire &
screenlayout &
mpd &
remaps &
slstatus &
picom &
xset r rate 300 50 &
if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
       eval `dbus-launch --sh-syntax --exit-with-session`
fi
